apiVersion: apps/v1

kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - name: load-balancer-example
        image: gcr.io/google-samples/node-hello:1.0
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
        ports:
        - containerPort: 8080
